### PR TITLE
Updated modal_window

### LINKED ISSUE #3: Alternative to modal window
> [!IMPORTANT]
> Read issue #1 first

I attach some videos to give a graphic idea of what I want to try to do.

It doesn't have to be exactly the same, but something close.

The vertical displacement with the click is optional.

https://github.com/user-attachments/assets/f58ae956-2370-40d4-b23f-af717e000707

https://github.com/user-attachments/assets/d47292a0-dd70-4c1e-8a3b-3ef2d666d59c

### PR DESCRIPTION
**Pull request by Swayam-hue**
Fixed issue #3 and updated the modal window transition from bottom to top vertically.

https://github.com/user-attachments/assets/83bb5c56-8790-44f6-aed8-00dd82d623a7

### CODE REVIEW

**Comment by nmarulo** [comment]
@Swayam-hue Please, can you make it so that the bottom menu is just at the border and the background is not above the bottom menu? similar to the example video of the issue.

**Comment by Swayam-hue** [comment]
> @Swayam-hue Please, can you make it so that the bottom menu is just at the border and the background is not above the bottom menu? similar to the example video of the issue.

@nmarulo Fixed the issue. Kindly check and let me know if anything else is required.

**Comment by nmarulo** [comment]
@Swayam-hue 
Don't close the PR, otherwise I think it doesn't count for the event.

You can work out the new changes here.

Also, I have realized a mistake I made because I wrote the issue wrong. 

The problem is: You can't overwrite the operation of the current `modal`, because on the same page there can be several `modal` (for example, [the `/shopping-list` page](https://github.com/despensa-app/despensa-html/tree/61982729f181fea4aa5cc69a2f6ba7bea5398d2b/shopping-list)). This means that the issue is about creating a new component and you can build on the “modal” component, but not overwrite it.

I updated the readme, if you want to see the resources used https://github.com/despensa-app/despensa-html?tab=readme-ov-file#recursos-utilizados

**Comment by Swayam-hue** [comment]
If a visual example can be provided of what the issue is to be solved maybe i can try solving it better. Otherwise the actual issue #4  according to the video example you gave has been completed by me.

**Comment by nmarulo** [comment]
@Swayam-hue It may be something, approximate, to this

https://github.com/user-attachments/assets/f5863004-6080-4ba6-a506-31dacf15689a

**Comment by Swayam-hue** [comment]
> @Swayam-hue It may be something, approximate, to this
> 
> 
> 
> https://github.com/user-attachments/assets/f5863004-6080-4ba6-a506-31dacf15689a
> 
> 
> 
> 

the alternate window button should trigger 2 different dialogue boxes if im right?

**Comment by nmarulo** [comment]
@Swayam-hue 

I have been doing some research and it looks like what I want to do is called a `drawer`.
This is an example, based on the video (`app-movil.mp4`) that I passed to you in the issue. I haven't found a better example:

[online demo](https://codi.link/PCFET0NUWVBFIGh0bWw+DQo8aHRtbCBsYW5nPSJlcyI+DQo8aGVhZD4NCiAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+DQogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPg0KICAgIDx0aXRsZT5WZW50YW5hIERlc2xpemFibGU8L3RpdGxlPg0KICAgIDxsaW5rIGhyZWY9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vYm9vdHN0cmFwQDUuMy4wL2Rpc3QvY3NzL2Jvb3RzdHJhcC5taW4uY3NzIiByZWw9InN0eWxlc2hlZXQiPg0KICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0ic3R5bGVzLmNzcyI+DQo8L2hlYWQ+DQo8Ym9keT4NCiAgICA8ZGl2IGNsYXNzPSJjb250YWluZXIgbWluLXZoLTEwMCBkLWZsZXggZmxleC1jb2x1bW4ganVzdGlmeS1jb250ZW50LWNlbnRlciBhbGlnbi1pdGVtcy1jZW50ZXIiPg0KICAgICAgICA8YnV0dG9uIGlkPSJvcGVuRHJhd2VyIiBjbGFzcz0iYnRuIGJ0bi1wcmltYXJ5Ij5BYnJpciBWZW50YW5hPC9idXR0b24+DQogICAgPC9kaXY+DQoNCiAgICA8ZGl2IGlkPSJkcmF3ZXIiIGNsYXNzPSJkcmF3ZXIiPg0KICAgICAgICA8ZGl2IGNsYXNzPSJkcmF3ZXItaGFuZGxlIj4NCiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImRyYXdlci1oYW5kbGUtYmFyIj48L2Rpdj4NCiAgICAgICAgPC9kaXY+DQogICAgICAgIDxidXR0b24gaWQ9ImNsb3NlRHJhd2VyIiBjbGFzcz0iYnRuLWNsb3NlIiBhcmlhLWxhYmVsPSJDbG9zZSI+PC9idXR0b24+DQogICAgICAgIDxkaXYgY2xhc3M9ImRyYXdlci1jb250ZW50Ij4NCiAgICAgICAgICAgIDxoMiBjbGFzcz0ibWItNCI+Q29udGVuaWRvIGRlIGxhIFZlbnRhbmE8L2gyPg0KICAgICAgICAgICAgPHA+RXN0ZSBlcyBlbCBjb250ZW5pZG8gZGUgbGEgdmVudGFuYSBkZXNsaXphYmxlLiBQdWVkZXMgYWdyZWdhciBtw6FzIGVsZW1lbnRvcyBhcXXDrS48L3A+DQogICAgICAgIDwvZGl2Pg0KICAgIDwvZGl2Pg0KDQogICAgPHNjcmlwdCBzcmM9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vYm9vdHN0cmFwQDUuMy4wL2Rpc3QvanMvYm9vdHN0cmFwLmJ1bmRsZS5taW4uanMiPjwvc2NyaXB0Pg0KICAgIDxzY3JpcHQgc3JjPSJzY3JpcHQuanMiPjwvc2NyaXB0Pg0KPC9ib2R5Pg0KPC9odG1sPg==%7CLmRyYXdlciB7DQogICAgcG9zaXRpb246IGZpeGVkOw0KICAgIGJvdHRvbTogMDsNCiAgICBsZWZ0OiAwOw0KICAgIHJpZ2h0OiAwOw0KICAgIGhlaWdodDogY2FsYygxMDAlIC0gMTAwcHgpOw0KICAgIGJhY2tncm91bmQtY29sb3I6IHdoaXRlOw0KICAgIGJvcmRlci10b3AtbGVmdC1yYWRpdXM6IDIwcHg7DQogICAgYm9yZGVyLXRvcC1yaWdodC1yYWRpdXM6IDIwcHg7DQogICAgYm94LXNoYWRvdzogMCAtMnB4IDEwcHggcmdiYSgwLCAwLCAwLCAwLjEpOw0KICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgxMDAlKTsNCiAgICB0cmFuc2l0aW9uOiB0cmFuc2Zvcm0gMC4zcyBlYXNlLWluLW91dDsNCn0NCg0KLmRyYXdlci5vcGVuIHsNCiAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoMCk7DQp9DQoNCi5kcmF3ZXItaGFuZGxlIHsNCiAgICBwb3NpdGlvbjogYWJzb2x1dGU7DQogICAgdG9wOiAwOw0KICAgIGxlZnQ6IDA7DQogICAgcmlnaHQ6IDA7DQogICAgaGVpZ2h0OiAzMnB4Ow0KICAgIGJhY2tncm91bmQtY29sb3I6ICNmOGY5ZmE7DQogICAgYm9yZGVyLXRvcC1sZWZ0LXJhZGl1czogMjBweDsNCiAgICBib3JkZXItdG9wLXJpZ2h0LXJhZGl1czogMjBweDsNCiAgICBjdXJzb3I6IG1vdmU7DQogICAgZGlzcGxheTogZmxleDsNCiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsNCiAgICBhbGlnbi1pdGVtczogY2VudGVyOw0KfQ0KDQouZHJhd2VyLWhhbmRsZS1iYXIgew0KICAgIHdpZHRoOiA2NHB4Ow0KICAgIGhlaWdodDogNHB4Ow0KICAgIGJhY2tncm91bmQtY29sb3I6ICNjZWQ0ZGE7DQogICAgYm9yZGVyLXJhZGl1czogMnB4Ow0KfQ0KDQouZHJhd2VyLWNvbnRlbnQgew0KICAgIHBhZGRpbmc6IDQ4cHggMTZweCAxNnB4Ow0KfQ0KDQojY2xvc2VEcmF3ZXIgew0KICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTsNCiAgICB0b3A6IDhweDsNCiAgICByaWdodDogOHB4Ow0KfQ==%7CZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsICgpID0+IHsNCiAgICBjb25zdCBkcmF3ZXIgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZHJhd2VyJyk7DQogICAgY29uc3Qgb3BlbkRyYXdlckJ0biA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvcGVuRHJhd2VyJyk7DQogICAgY29uc3QgY2xvc2VEcmF3ZXJCdG4gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnY2xvc2VEcmF3ZXInKTsNCiAgICBjb25zdCBkcmF3ZXJIYW5kbGUgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcuZHJhd2VyLWhhbmRsZScpOw0KDQogICAgbGV0IGlzRHJhZ2dpbmcgPSBmYWxzZTsNCiAgICBsZXQgc3RhcnRZOw0KICAgIGxldCBzdGFydFRyYW5zbGF0ZVk7DQoNCiAgICBvcGVuRHJhd2VyQnRuLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4gew0KICAgICAgICBkcmF3ZXIuY2xhc3NMaXN0LmFkZCgnb3BlbicpOw0KICAgIH0pOw0KDQogICAgY2xvc2VEcmF3ZXJCdG4uYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7DQogICAgICAgIGRyYXdlci5jbGFzc0xpc3QucmVtb3ZlKCdvcGVuJyk7DQogICAgfSk7DQoNCiAgICBkcmF3ZXJIYW5kbGUuYWRkRXZlbnRMaXN0ZW5lcignbW91c2Vkb3duJywgc3RhcnREcmFnZ2luZyk7DQogICAgZHJhd2VySGFuZGxlLmFkZEV2ZW50TGlzdGVuZXIoJ3RvdWNoc3RhcnQnLCBzdGFydERyYWdnaW5nKTsNCg0KICAgIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ21vdXNlbW92ZScsIGRyYWcpOw0KICAgIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ3RvdWNobW92ZScsIGRyYWcpOw0KDQogICAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignbW91c2V1cCcsIHN0b3BEcmFnZ2luZyk7DQogICAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcigndG91Y2hlbmQnLCBzdG9wRHJhZ2dpbmcpOw0KDQogICAgZnVuY3Rpb24gc3RhcnREcmFnZ2luZyhlKSB7DQogICAgICAgIGlzRHJhZ2dpbmcgPSB0cnVlOw0KICAgICAgICBzdGFydFkgPSBlLmNsaWVudFkgfHwgZS50b3VjaGVzWzBdLmNsaWVudFk7DQogICAgICAgIHN0YXJ0VHJhbnNsYXRlWSA9IGdldFRyYW5zbGF0ZVkoKTsNCiAgICAgICAgZHJhd2VyLnN0eWxlLnRyYW5zaXRpb24gPSAnbm9uZSc7DQogICAgfQ0KDQogICAgZnVuY3Rpb24gZHJhZyhlKSB7DQogICAgICAgIGlmICghaXNEcmFnZ2luZykgcmV0dXJuOw0KICAgICAgICBjb25zdCBjdXJyZW50WSA9IGUuY2xpZW50WSB8fCBlLnRvdWNoZXNbMF0uY2xpZW50WTsNCiAgICAgICAgY29uc3QgZGVsdGFZID0gY3VycmVudFkgLSBzdGFydFk7DQogICAgICAgIGNvbnN0IG5ld1RyYW5zbGF0ZVkgPSBNYXRoLm1heCgwLCBzdGFydFRyYW5zbGF0ZVkgKyBkZWx0YVkpOw0KICAgICAgICBkcmF3ZXIuc3R5bGUudHJhbnNmb3JtID0gYHRyYW5zbGF0ZVkoJHtuZXdUcmFuc2xhdGVZfXB4KWA7DQogICAgfQ0KDQogICAgZnVuY3Rpb24gc3RvcERyYWdnaW5nKCkgew0KICAgICAgICBpZiAoIWlzRHJhZ2dpbmcpIHJldHVybjsNCiAgICAgICAgaXNEcmFnZ2luZyA9IGZhbHNlOw0KICAgICAgICBkcmF3ZXIuc3R5bGUudHJhbnNpdGlvbiA9ICd0cmFuc2Zvcm0gMC4zcyBlYXNlLWluLW91dCc7DQogICAgICAgIGNvbnN0IGN1cnJlbnRUcmFuc2xhdGVZID0gZ2V0VHJhbnNsYXRlWSgpOw0KICAgICAgICBpZiAoY3VycmVudFRyYW5zbGF0ZVkgPiBkcmF3ZXIub2Zmc2V0SGVpZ2h0IC8gMikgew0KICAgICAgICAgICAgZHJhd2VyLnN0eWxlLnRyYW5zZm9ybSA9IGB0cmFuc2xhdGVZKCR7ZHJhd2VyLm9mZnNldEhlaWdodH1weClgOw0KICAgICAgICAgICAgc2V0VGltZW91dCgoKSA9PiB7DQogICAgICAgICAgICAgICAgZHJhd2VyLmNsYXNzTGlzdC5yZW1vdmUoJ29wZW4nKTsNCiAgICAgICAgICAgICAgICBkcmF3ZXIuc3R5bGUudHJhbnNmb3JtID0gJyc7DQogICAgICAgICAgICB9LCAzMDApOw0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgZHJhd2VyLnN0eWxlLnRyYW5zZm9ybSA9ICd0cmFuc2xhdGVZKDApJzsNCiAgICAgICAgfQ0KICAgIH0NCg0KICAgIGZ1bmN0aW9uIGdldFRyYW5zbGF0ZVkoKSB7DQogICAgICAgIGNvbnN0IHRyYW5zZm9ybSA9IHdpbmRvdy5nZXRDb21wdXRlZFN0eWxlKGRyYXdlcikuZ2V0UHJvcGVydHlWYWx1ZSgndHJhbnNmb3JtJyk7DQogICAgICAgIGNvbnN0IG1hdHJpeCA9IG5ldyBET01NYXRyaXgodHJhbnNmb3JtKTsNCiAgICAgICAgcmV0dXJuIG1hdHJpeC5tNDI7DQogICAgfQ0KfSk7)

I leave a video in case you can't see the demo correctly:

https://github.com/user-attachments/assets/fce0c6fa-3cf1-4f4c-9a78-998441278990

Just for comment, it seems that there is in bootstrap 5, something similar, although I have to use 4, for now.

**Pull request closed without merging**
